HOSTS:
  centos-6-vagrant:
    platform: el-6-x86_64
    hypervisor: vagrant
    box: boxcutter-centos73
    mount_folders:
      wget_cache:
        from: /tmp/vagrant-cache/wget
        to: /var/cache/wget
      yum_cache:
        from: /tmp/vagrant-cache/yum/centos-6-vagrant
        to: /var/cache/yum
CONFIG:
  type: foss
  log_level: debug
